apiVersion: v1
kind: Namespace
metadata:
  name: devops-app

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: devops-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: frontend-image:latest  # Replace with your actual image
          ports:
            - containerPort: 3000
          env:
            - name: API_URL
              value: http://backend:8080

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: devops-app
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: frontend

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: devops-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: backend-image:latest  # Replace with your actual image
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: EMS-postgres
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: EMS
            - name: DB_USER
              value: EMS
            - name: DB_PASSWORD
              value: EMS
            - name: ALLOWED_ORIGINS
              value: gorunmain.go

---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: devops-app
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: backend

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: devops-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: postgres:9.6-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: EMS
            - name: POSTGRES_USER
              value: EMS
            - name: POSTGRES_PASSWORD
              value: EMS

---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: devops-app
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: db
